spring:
  application:
    name: bread-budget-backend

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5433/budget-tracker

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: a nice client id
            client-secret: a nice client secret
            scope: profile, email

security:
  jwt:
    secret-key: nice jwt secret
    expiration-time: 100000
